-- V11: HOJ P3 - 정답 코드(참고 풀이) + 북마크 (docs 결정 13, hoj/api.md 6절·7절, 2026-09-20 PM)
--
-- 왜 지금 이 두 테이블인가
--   - 랭킹·채점 현황·사용자 페이지·다른 사람 풀이는 전부 기존 submissions·judge_results 를 읽기만 한다 - 새 테이블이 필요 없다.
--   - 정답 코드: 문제마다 언어별 참고 풀이 1건을 서버에 둔다. 운영진이 채점 설정·질문 답변 때 참고하는 용도라
--     운영진 이상만 읽고 쓰며 학생에게는 존재도 보이지 않는다(풀이 공개 규칙 "맞힌 뒤에만" 과 충돌). 문제 은행 레포의
--     solutions/sol.<ext> 를 가져오기 때 함께 읽어 넣는다.
--   - 북마크: 사용자가 문제에 붙이는 표시 - 열이 둘뿐인 관계 테이블이라 복합 PK, PUT/DELETE 멱등.

-- ---------------------------------------------------------------------------
-- 1. 정답 코드 - (problem_id, language) 하나에 코드 하나. 언어 값은 제출 언어와 같은 표기 (C, C++, Java, Python 3, JavaScript, TypeScript)
-- ---------------------------------------------------------------------------
create table problem_solutions (
    id         bigint generated by default as identity primary key,
    problem_id bigint       not null,
    language   varchar(30)  not null,
    code_text  text         not null,
    updated_by bigint       not null,   -- 마지막으로 저장한 운영진. 가져오기면 요청한 관리자
    updated_at timestamp(6) with time zone not null,
    constraint uk_problem_solutions_problem_language unique (problem_id, language),
    constraint fk_problem_solutions_problem foreign key (problem_id) references problems (id),
    constraint fk_problem_solutions_updated_by foreign key (updated_by) references users (id)
);

-- ---------------------------------------------------------------------------
-- 2. 북마크 - 목록·상세의 bookmarked 로만 읽는다 (별도 GET 없음)
-- ---------------------------------------------------------------------------
create table problem_bookmarks (
    user_id    bigint not null,
    problem_id bigint not null,
    created_at timestamp(6) with time zone not null,
    constraint pk_problem_bookmarks primary key (user_id, problem_id),
    constraint fk_problem_bookmarks_user foreign key (user_id) references users (id),
    constraint fk_problem_bookmarks_problem foreign key (problem_id) references problems (id)
);
create index idx_problem_bookmarks_problem on problem_bookmarks (problem_id);   -- 문제 삭제 연쇄
