-- V2: 공지사항 (docs notice/design.md) - 전체 공지(cohort_id NULL, 관리자)와 분반 공지(cohort_id 값, 그 분반 운영진 이상)
-- 학생 화면 목록 = 전체 공지 + 소속 분반 공지, 필독(pinned) 먼저 → 최신순. 수정 시각 열 없음 (questions 와 동일 규칙)

create table notices (
    id         bigint generated by default as identity primary key,
    cohort_id  bigint,                                  -- NULL = 전체 공지 / 값 = 분반 공지
    author_id  bigint       not null,                   -- 작성자 - 등록 시 요청자로 고정. 소속 해제 후에도 글은 남는다
    title      varchar(200) not null,
    content    text         not null,                   -- 최대 10000자는 서비스 검증
    pinned     boolean      not null default false,     -- 필독 - 목록 최상단 고정
    created_at timestamp(6) with time zone not null,
    constraint fk_notices_cohort foreign key (cohort_id) references cohorts (id),
    constraint fk_notices_author foreign key (author_id) references users (id)
);
create index idx_notices_cohort_created on notices (cohort_id, created_at);   -- 분반별 최신순 (전체 공지는 NULL 그룹)
create index idx_notices_author on notices (author_id);
