-- V3: 출석부 (docs attendance/design.md) - 차시(sessions)와 출석 기록(attendances)
-- 차시는 분반 안에서 번호가 유일하고 날짜(held_on, KST 달력일)를 갖는다. assignments.session_no 는 정수 그대로(FK 없음, 같은 번호 체계 - 결정 1)
-- 출석 기록이 없는 (차시, 수강생) 조합은 "미확인" - 상태 값이 아니라 행 부재 (결정 2)

create table sessions (
    id         bigint generated by default as identity primary key,
    cohort_id  bigint       not null,
    session_no integer      not null,                   -- 차시 번호 - 등록 시 생략하면 최대 + 1
    title      varchar(100),                            -- 예: 포인터와 배열 (선택)
    held_on    date         not null,                   -- 수업 날짜 - 유일하게 date 타입인 열 (결정 8)
    created_at timestamp(6) with time zone not null,
    constraint fk_sessions_cohort foreign key (cohort_id) references cohorts (id),
    constraint uk_sessions_cohort_no unique (cohort_id, session_no)
);
create index idx_sessions_cohort_held on sessions (cohort_id, held_on);   -- 분반 안 날짜순 목록

create table attendances (
    id         bigint generated by default as identity primary key,
    session_id bigint       not null,
    user_id    bigint       not null,                   -- 수강생
    status     varchar(20)  not null,                   -- PRESENT / LATE / ABSENT
    checked_at timestamp(6) with time zone not null,    -- 표시(마지막 변경) 시각
    checked_by bigint       not null,                   -- 표시한 운영진
    constraint fk_attendances_session foreign key (session_id) references sessions (id),
    constraint fk_attendances_user foreign key (user_id) references users (id),
    constraint fk_attendances_checked_by foreign key (checked_by) references users (id),
    constraint uk_attendances_session_user unique (session_id, user_id)
);
create index idx_attendances_user on attendances (user_id);   -- 학생 자기 기록·누계 조회
