-- V4: Q&A 답변 (docs qna/design.md 결정 11, 2026-09-14 편입) - 질문 글에 달리는 답변
-- 분반 소속 누구나 작성, 수정은 작성자, 삭제는 작성자 또는 운영진 이상 (질문과 같은 규칙). 질문 삭제 시 서비스가 연쇄 삭제

create table answers (
    id          bigint generated by default as identity primary key,
    question_id bigint       not null,
    author_id   bigint       not null,   -- 작성자 - 등록 시 요청자로 고정
    content     text         not null,   -- 최대 10000자는 서비스 검증
    created_at  timestamp(6) with time zone not null,
    constraint fk_answers_question foreign key (question_id) references questions (id),
    constraint fk_answers_author foreign key (author_id) references users (id)
);
create index idx_answers_question_created on answers (question_id, created_at);   -- 질문 안 오래된 순(대화 흐름)
create index idx_answers_author on answers (author_id);
