-- V6: 자동 채점 (docs judge/design.md 결정 1·12, db/schema.md 결정 15) - 과제의 테스트케이스 + 제출의 채점 결과 1행
-- 테스트케이스가 1개 이상이면 "자동 채점 문제". 판정은 서버 비교기가 내리고, 실행만 채점 엔진(Judge0)이 한다

-- 과제별 실행 제한 - null 이면 서버 기본값(2초·256MB, ondal.judge.default-*)
alter table assignments add column time_limit_ms   integer;
alter table assignments add column memory_limit_mb integer;

create table test_cases (
    id              bigint generated by default as identity primary key,
    assignment_id   bigint  not null,
    position        integer not null,            -- 0부터, 저장 순서 = 실행 순서. 통째 교체(PUT)로만 바뀐다
    input           text    not null,            -- 표준 입력 (빈 문자열 허용 - 입력 없는 문제)
    expected_output text    not null,            -- 기대 출력 - 비교는 줄 끝 공백·마지막 빈 줄 무시 (OutputComparator)
    is_public       boolean not null default false,   -- 학생에게 예시로 보이고 채점 결과에서 실제 출력까지 노출
    constraint fk_test_cases_assignment foreign key (assignment_id) references assignments (id)
);
create index idx_test_cases_assignment on test_cases (assignment_id, position);

create table judge_results (
    submission_id   bigint  primary key,          -- 제출 1건에 결과 1행 - 재채점은 덮어쓰기 (채점 이력 없음, 제출 이력이 이미 append-only)
    assignment_id   bigint  not null,             -- 재채점·삭제 연쇄 조회용 (submissions.assignment_id 와 같은 값)
    status          varchar(10) not null,         -- PENDING / RUNNING / DONE / ERROR
    verdict         varchar(20),                  -- DONE·ERROR 일 때만: ACCEPTED / WRONG_ANSWER / TIME_LIMIT / MEMORY_LIMIT / RUNTIME_ERROR / COMPILE_ERROR / JUDGE_ERROR
    passed_cases    integer not null default 0,
    total_cases     integer not null default 0,
    max_time_ms     integer,
    max_memory_kb   integer,
    compile_output  text,                         -- COMPILE_ERROR 일 때 컴파일러 메시지 (8KB 로 잘라 저장)
    case_results    jsonb,                        -- 케이스별 [{position, verdict, timeMs, memoryKb, actualOutput, truncated}] - 항상 제출 단위로 통째 읽고 쓴다
    attempts        integer not null default 0,   -- 엔진 호출 시도 횟수 - 백오프·포기 판단
    created_at      timestamp(6) with time zone not null,
    judged_at       timestamp(6) with time zone,
    constraint fk_judge_results_submission foreign key (submission_id) references submissions (id),
    constraint fk_judge_results_assignment foreign key (assignment_id) references assignments (id)
);
create index idx_judge_results_assignment on judge_results (assignment_id);
create index idx_judge_results_status on judge_results (status);
