-- V7: 문제 라이브러리 분리 + 태그 + HOJ 연습 제출 (docs judge/design.md 결정 17, db/schema.md 결정 16)
--
-- 왜 problems 를 떼어내는가
--   - 지금까지 "문제 = 과제" 였다 - 같은 문제를 다음 학기에 다시 내면 과제 행이 새로 생기고 test_cases 까지 복제된다.
--     한쪽 테스트케이스를 고쳐도 다른 쪽은 그대로여서 채점 기준이 갈라진다 (가정이 아니라 구조상 확정).
--   - problem_no 가 전역 유일인데 분반 종속 테이블(assignments)에 있던 것도 두 개념이 뭉쳐 있다는 신호였다.
--   - 분리 후: assignment = "이 문제를 이 분반에 이 마감으로 배정한 것". 재출제는 행 하나 추가일 뿐 문제는 하나를 공유한다.
--
-- 되돌릴 수 없는 마이그레이션(열 삭제 포함) - 운영 적용 전 DB 덤프 백업 필수.

-- ---------------------------------------------------------------------------
-- 1. 문제 라이브러리
-- ---------------------------------------------------------------------------
create table problems (
    id              bigint generated by default as identity primary key,
    problem_no      integer      not null,   -- 전역 유일, 1000부터. assignments 에서 이관 (결정 9 승계)
    title           varchar(200) not null,
    description     text,
    time_limit_ms   integer,                 -- null 이면 서버 기본값(ondal.judge.default-*)
    memory_limit_mb integer,
    created_by      bigint,                  -- 출제자. 이관된 기존 문제는 작성자를 알 수 없어 null
    created_at      timestamp(6) with time zone not null,
    updated_at      timestamp(6) with time zone not null,
    constraint uk_problems_problem_no unique (problem_no),
    constraint fk_problems_created_by foreign key (created_by) references users (id)
);

-- 기존 과제 1건 = 문제 1건으로 이관. problem_no 가 전역 유일이라 1:1 이 보장된다
insert into problems (problem_no, title, description, time_limit_ms, memory_limit_mb, created_by, created_at, updated_at)
select problem_no, title, description, time_limit_ms, memory_limit_mb, null, created_at, created_at
from assignments;

-- ---------------------------------------------------------------------------
-- 2. assignments = 배정 (문제 속성은 problems 로 넘긴다)
-- ---------------------------------------------------------------------------
alter table assignments add column problem_id bigint;
update assignments a set problem_id = p.id from problems p where p.problem_no = a.problem_no;
alter table assignments alter column problem_id set not null;
alter table assignments add constraint fk_assignments_problem foreign key (problem_id) references problems (id);
create index idx_assignments_problem on assignments (problem_id);

-- 열을 지우면 그 열에 걸린 인덱스·제약(uk_assignments_problem_no)도 함께 사라진다
alter table assignments drop column problem_no;
alter table assignments drop column title;
alter table assignments drop column description;
alter table assignments drop column time_limit_ms;
alter table assignments drop column memory_limit_mb;

-- ---------------------------------------------------------------------------
-- 3. 테스트케이스는 문제의 것 - 복제 대신 공유
-- ---------------------------------------------------------------------------
alter table test_cases add column problem_id bigint;
update test_cases t set problem_id = a.problem_id from assignments a where a.id = t.assignment_id;
alter table test_cases alter column problem_id set not null;
alter table test_cases add constraint fk_test_cases_problem foreign key (problem_id) references problems (id);
alter table test_cases drop column assignment_id;
create index idx_test_cases_problem on test_cases (problem_id, position);

-- ---------------------------------------------------------------------------
-- 4. 채점 결과도 문제 기준 - 채점은 본래 문제의 함수(테스트케이스·제한이 problems 소유)
--    과제 단위 재채점은 submissions.assignment_id 로 대상을 추린다
-- ---------------------------------------------------------------------------
alter table judge_results add column problem_id bigint;
update judge_results r set problem_id = a.problem_id from assignments a where a.id = r.assignment_id;
alter table judge_results alter column problem_id set not null;
alter table judge_results add constraint fk_judge_results_problem foreign key (problem_id) references problems (id);
alter table judge_results drop column assignment_id;
create index idx_judge_results_problem on judge_results (problem_id);

-- ---------------------------------------------------------------------------
-- 5. HOJ 연습 제출 - 분반 과제 제출과 파이프라인 하나를 공유한다 (CLAUDE.md 원칙 1)
--    제출은 "과제에 낸 것" 또는 "문제를 연습으로 푼 것" 둘 중 정확히 하나
-- ---------------------------------------------------------------------------
alter table submissions alter column assignment_id drop not null;
alter table submissions add column problem_id bigint;
alter table submissions add constraint fk_submissions_problem foreign key (problem_id) references problems (id);
alter table submissions add constraint chk_submissions_target
    check (num_nonnulls(assignment_id, problem_id) = 1);
-- 연습 제출은 코드만 - zip·링크는 운영진이 확인해야 의미가 있는데 연습에는 확인할 운영진이 없다
alter table submissions add constraint chk_submissions_practice_code
    check (problem_id is null or type = 'CODE');
-- 연습 제출에는 마감도 코멘트도 없다
alter table submissions add constraint chk_submissions_practice_no_comment
    check (problem_id is null or (mentor_comment is null and commented_by is null and commented_at is null));
create index idx_submissions_problem_user on submissions (problem_id, user_id, submitted_at);

-- ---------------------------------------------------------------------------
-- 6. 태그 - 문제를 알고리즘·자료구조로 묶는다. 생성·수정·삭제는 전역 ADMIN 만(서비스 판정)
-- ---------------------------------------------------------------------------
create table tags (
    id         bigint generated by default as identity primary key,
    name       varchar(40) not null,   -- 표기 흔들림(DP / 다이나믹프로그래밍 / dp)을 막으려고 생성 권한을 ADMIN 으로 묶는다
    created_at timestamp(6) with time zone not null,
    constraint uk_tags_name unique (name)
);

create table problem_tags (
    problem_id bigint not null,
    tag_id     bigint not null,
    constraint pk_problem_tags primary key (problem_id, tag_id),
    constraint fk_problem_tags_problem foreign key (problem_id) references problems (id),
    constraint fk_problem_tags_tag foreign key (tag_id) references tags (id)
);
create index idx_problem_tags_tag on problem_tags (tag_id);   -- 태그로 문제 찾기
